title: Lunafae Graves
email: lunafaegraves@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Want to get in contact with me? This is the best way!
  Big things are coming, and I can't wait to share them all with you!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://LunafaeGraves.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  LunafaeGraves

# Build settings
theme: hacked-jekyll
plugins:
  - jekyll-feed
color_punct: teal-6
quotes: true
commas: true